#!/bin/bash
# Full Research Workflow Example
# Demonstrates a complete research workflow: search -> extract -> analyze

# Check if API keys are set
if [ -z "$SEARCHAPI_KEY" ] || [ -z "$JINA_API_KEY" ]; then
  echo "Error: Required environment variables not set"
  echo "Set them with:"
  echo "  export SEARCHAPI_KEY='your_key_here'"
  echo "  export JINA_API_KEY='your_key_here'"
  exit 1
fi

# Configuration
QUERY="${1:-artificial intelligence trends 2024}"
OUTPUT_DIR="research_output"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

# Create output directory
mkdir -p "$OUTPUT_DIR"

echo "=== Internet Research Workflow ==="
echo "Query: $QUERY"
echo "Output Directory: $OUTPUT_DIR"
echo "Timestamp: $TIMESTAMP"
echo ""

# Step 1: Search
echo "Step 1: Searching Google..."
ENCODED_QUERY=$(echo "$QUERY" | sed 's/ /+/g')
SEARCH_FILE="$OUTPUT_DIR/search_${TIMESTAMP}.json"

curl -s "https://www.searchapi.io/api/v1/search?engine=google&api_key=${SEARCHAPI_KEY}&q=${ENCODED_QUERY}" \
  > "$SEARCH_FILE"

echo "✓ Search results saved to: $SEARCH_FILE"
echo ""

# Step 2: Extract top URLs
echo "Step 2: Extracting top 3 URLs..."
URLS=$(jq -r '.organic_results[0:3] | .[] | .link' "$SEARCH_FILE")

URL_COUNT=0
for URL in $URLS; do
  URL_COUNT=$((URL_COUNT + 1))
  echo "  [$URL_COUNT] Extracting: $URL"
  
  CONTENT_FILE="$OUTPUT_DIR/content_${URL_COUNT}_${TIMESTAMP}.txt"
  
  curl -s "https://r.jina.ai/${URL}" \
    -H "Authorization: Bearer ${JINA_API_KEY}" \
    -H "X-Return-Format: text" \
    > "$CONTENT_FILE"
  
  echo "      ✓ Saved to: $CONTENT_FILE"
done

echo ""

# Step 3: Create summary
echo "Step 3: Creating research summary..."
SUMMARY_FILE="$OUTPUT_DIR/summary_${TIMESTAMP}.md"

cat > "$SUMMARY_FILE" << SUMMARY
# Research Summary: $QUERY

**Date:** $(date)
**Query:** $QUERY

## Search Results

$(jq -r '.organic_results[0:5] | .[] | "### [\(.position)] \(.title)\n\n**URL:** \(.link)\n\n**Snippet:** \(.snippet)\n"' "$SEARCH_FILE")

## Extracted Content

Content extracted from top 3 URLs and saved to:
$(ls -1 "$OUTPUT_DIR"/content_*_${TIMESTAMP}.txt | sed 's/^/- /')

---
*Generated by Internet Research Skill*
SUMMARY

echo "✓ Summary saved to: $SUMMARY_FILE"
echo ""
echo "=== Research Complete ==="
echo "All files saved to: $OUTPUT_DIR/"
ls -lh "$OUTPUT_DIR"/*_${TIMESTAMP}.*
